CREATE TABLE [dbo].[CALLCENTER_HEADERQUARTERS_NODE_RELATIONSHIP] (
    [CALLCENTER_NODE_ID]              INT     NOT NULL,
    [HEADERQUARTER_NODE_ID]           INT     NOT NULL,
    [CALLCENTER_ORGANIZATION_TYPE]    TINYINT NOT NULL,
    [HEADERQUARTER_ORGANIZATION_TYPE] TINYINT NOT NULL,
    CONSTRAINT [PK_CALLCENTER_HEADERQUARTERS_NODE_RELATIONSHIP] PRIMARY KEY CLUSTERED ([CALLCENTER_NODE_ID] ASC, [HEADERQUARTER_NODE_ID] ASC, [CALLCENTER_ORGANIZATION_TYPE] ASC, [HEADERQUARTER_ORGANIZATION_TYPE] ASC),
    CONSTRAINT [FK_CALLCENTER_HEADERQUARTERS_NODE_RELATIONSHIP_CALLCENTER_NODE] FOREIGN KEY ([CALLCENTER_NODE_ID], [CALLCENTER_ORGANIZATION_TYPE]) REFERENCES [dbo].[CALLCENTER_NODE] ([NODE_ID], [ORGANIZATION_TYPE]),
    CONSTRAINT [FK_CALLCENTER_HEADERQUARTERS_NODE_RELATIONSHIP_HEADQUARTERS_NODE] FOREIGN KEY ([HEADERQUARTER_NODE_ID], [HEADERQUARTER_ORGANIZATION_TYPE]) REFERENCES [dbo].[HEADQUARTERS_NODE] ([NODE_ID], [ORGANIZATION_TYPE])
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'客服組織服務企業別主檔', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CALLCENTER_HEADERQUARTERS_NODE_RELATIONSHIP';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'客服中心組織結點', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CALLCENTER_HEADERQUARTERS_NODE_RELATIONSHIP', @level2type = N'COLUMN', @level2name = N'CALLCENTER_NODE_ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'總部組織結點', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CALLCENTER_HEADERQUARTERS_NODE_RELATIONSHIP', @level2type = N'COLUMN', @level2name = N'HEADERQUARTER_NODE_ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'客服中心組織型態', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CALLCENTER_HEADERQUARTERS_NODE_RELATIONSHIP', @level2type = N'COLUMN', @level2name = N'CALLCENTER_ORGANIZATION_TYPE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'總部組織型態', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CALLCENTER_HEADERQUARTERS_NODE_RELATIONSHIP', @level2type = N'COLUMN', @level2name = N'HEADERQUARTER_ORGANIZATION_TYPE';

