CREATE TABLE [dbo].[CASE_FINISH_REASON_DATA_RELATIONSHIP] (
    [CASE_ID]   CHAR (14) NOT NULL,
    [REASON_ID] INT       NOT NULL,
    CONSTRAINT [PK_CASE_FINISH_REASON_DATA_RELATIONSHIP] PRIMARY KEY CLUSTERED ([CASE_ID] ASC, [REASON_ID] ASC),
    CONSTRAINT [FK_CASE_FINISH_REASON_DATA_RELATIONSHIP_CASE] FOREIGN KEY ([CASE_ID]) REFERENCES [dbo].[CASE] ([CASE_ID]),
    CONSTRAINT [FK_CASE_FINISH_REASON_DATA_RELATIONSHIP_CASE_FINISH_REASON_DATA] FOREIGN KEY ([REASON_ID]) REFERENCES [dbo].[CASE_FINISH_REASON_DATA] ([ID])
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'案件-結案處置原因關聯檔', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CASE_FINISH_REASON_DATA_RELATIONSHIP';

