CREATE TABLE [dbo].[CASE_ASSIGNMENT_COMPLAINT_INVOICE_CODE] (
    [DATE]        CHAR (4) NOT NULL,
    [BU_CODE]     CHAR (3) NOT NULL,
    [SERIAL_CODE] INT      CONSTRAINT [DF_CASE_ASSIGNMENT_COMPLAINT_INVOICE_CODE_SERIAL_CODE] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_CASE_ASSIGNMENT_COMPLAINT_INVOICE_CODE] PRIMARY KEY CLUSTERED ([DATE] ASC, [BU_CODE] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'yyyyMM', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CASE_ASSIGNMENT_COMPLAINT_INVOICE_CODE', @level2type = N'COLUMN', @level2name = N'DATE';

