CREATE TABLE [dbo].[OFFICIAL_EMAIL_EFFECTIVE_DATA] (
    [NODE_ID]           INT             NOT NULL,
    [ORGANIZATION_TYPE] TINYINT         NOT NULL,
    [MESSAGE_ID]        NVARCHAR (250)  NOT NULL,
    [SUBJECT]           NVARCHAR (255)  NULL,
    [FROM_NAME]         NVARCHAR (50)   NULL,
    [FROM_ADDRESS]      NVARCHAR (100)  NULL,
    [BODY]              NVARCHAR (4000) NULL,
    [RECEIVED_DATETIME] DATETIME        NOT NULL,
    [FILE_PATH]         NVARCHAR (1024) NOT NULL,
    [CREATE_DATETIME]   DATETIME        NOT NULL,
    [CASE_ID]           CHAR (14)       NULL,
    [EMAIL_GROUP_ID]    INT             NOT NULL,
    [HAS_ATTACHMENT]    BIT             CONSTRAINT [DF_OFFICIAL_EMAIL_EFFECTIVE_DATA_HAS_ATTACHMENT] DEFAULT ((0)) NOT NULL,
    [J_CONTENT]         NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_OFFICIAL_EMAIL_EFFECTIVE_DATA] PRIMARY KEY CLUSTERED ([NODE_ID] ASC, [MESSAGE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [_dta_index_OFFICIAL_EMAIL_EFFECTIVE_DATA_23_1325963800__K1_K8D_2_3_4_5_6_7_9_10_11_12_13]
    ON [dbo].[OFFICIAL_EMAIL_EFFECTIVE_DATA]([NODE_ID] ASC, [RECEIVED_DATETIME] DESC)
    INCLUDE([ORGANIZATION_TYPE], [MESSAGE_ID], [SUBJECT], [FROM_NAME], [FROM_ADDRESS], [BODY], [FILE_PATH], [CREATE_DATETIME], [CASE_ID], [EMAIL_GROUP_ID], [HAS_ATTACHMENT]);


GO
CREATE NONCLUSTERED INDEX [_dta_index_OFFICIAL_EMAIL_EFFECTIVE_DATA_23_1325963800__K1_2_3_4_5_6_7_8_9_10_11_12_13]
    ON [dbo].[OFFICIAL_EMAIL_EFFECTIVE_DATA]([NODE_ID] ASC)
    INCLUDE([ORGANIZATION_TYPE], [MESSAGE_ID], [SUBJECT], [FROM_NAME], [FROM_ADDRESS], [BODY], [RECEIVED_DATETIME], [FILE_PATH], [CREATE_DATETIME], [CASE_ID], [EMAIL_GROUP_ID], [HAS_ATTACHMENT]);


GO
CREATE NONCLUSTERED INDEX [_dta_index_OFFICIAL_EMAIL_EFFECTIVE_DATA_23_1325963800__K12]
    ON [dbo].[OFFICIAL_EMAIL_EFFECTIVE_DATA]([EMAIL_GROUP_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [_dta_index_OFFICIAL_EMAIL_EFFECTIVE_DATA_23_1325963800__K1]
    ON [dbo].[OFFICIAL_EMAIL_EFFECTIVE_DATA]([NODE_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [_dta_index_OFFICIAL_EMAIL_EFFECTIVE_DATA_23_1325963800__K12_K3_1_2_4_5_6_7_8_9_10_11_13]
    ON [dbo].[OFFICIAL_EMAIL_EFFECTIVE_DATA]([EMAIL_GROUP_ID] ASC, [MESSAGE_ID] ASC)
    INCLUDE([NODE_ID], [ORGANIZATION_TYPE], [SUBJECT], [FROM_NAME], [FROM_ADDRESS], [BODY], [RECEIVED_DATETIME], [FILE_PATH], [CREATE_DATETIME], [CASE_ID], [HAS_ATTACHMENT]);


GO
CREATE NONCLUSTERED INDEX [_dta_index_OFFICIAL_EMAIL_EFFECTIVE_DATA_23_1325963800__K4_3_6]
    ON [dbo].[OFFICIAL_EMAIL_EFFECTIVE_DATA]([SUBJECT] ASC)
    INCLUDE([MESSAGE_ID], [FROM_ADDRESS]);


GO
CREATE NONCLUSTERED INDEX [_dta_index_OFFICIAL_EMAIL_EFFECTIVE_DATA_23_1325963800__K1_K5_12]
    ON [dbo].[OFFICIAL_EMAIL_EFFECTIVE_DATA]([NODE_ID] ASC, [FROM_NAME] ASC)
    INCLUDE([EMAIL_GROUP_ID]);


GO
CREATE NONCLUSTERED INDEX [_dta_index_OFFICIAL_EMAIL_EFFECTIVE_DATA_23_1325963800__K5_3_11]
    ON [dbo].[OFFICIAL_EMAIL_EFFECTIVE_DATA]([FROM_NAME] ASC)
    INCLUDE([MESSAGE_ID], [CASE_ID]);


GO
CREATE NONCLUSTERED INDEX [_dta_index_OFFICIAL_EMAIL_EFFECTIVE_DATA_23_1325963800__K2_K12]
    ON [dbo].[OFFICIAL_EMAIL_EFFECTIVE_DATA]([ORGANIZATION_TYPE] ASC, [EMAIL_GROUP_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [_dta_index_OFFICIAL_EMAIL_EFFECTIVE_DATA_23_1325963800__K1_K5]
    ON [dbo].[OFFICIAL_EMAIL_EFFECTIVE_DATA]([NODE_ID] ASC, [FROM_NAME] ASC);


GO
CREATE NONCLUSTERED INDEX [_dta_index_OFFICIAL_EMAIL_EFFECTIVE_DATA_23_1325963800__K2_K1]
    ON [dbo].[OFFICIAL_EMAIL_EFFECTIVE_DATA]([ORGANIZATION_TYPE] ASC, [NODE_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [_dta_index_OFFICIAL_EMAIL_EFFECTIVE_DATA_23_1325963800__K1_K11_2_3_4_5_6_7_8_9_10_12_13]
    ON [dbo].[OFFICIAL_EMAIL_EFFECTIVE_DATA]([NODE_ID] ASC, [CASE_ID] ASC)
    INCLUDE([ORGANIZATION_TYPE], [MESSAGE_ID], [SUBJECT], [FROM_NAME], [FROM_ADDRESS], [BODY], [RECEIVED_DATETIME], [FILE_PATH], [CREATE_DATETIME], [EMAIL_GROUP_ID], [HAS_ATTACHMENT]);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'官網來信通知(有效清單)', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OFFICIAL_EMAIL_EFFECTIVE_DATA';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'BU名稱', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OFFICIAL_EMAIL_EFFECTIVE_DATA', @level2type = N'COLUMN', @level2name = N'NODE_ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'組織型態', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OFFICIAL_EMAIL_EFFECTIVE_DATA', @level2type = N'COLUMN', @level2name = N'ORGANIZATION_TYPE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'信件 ID', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OFFICIAL_EMAIL_EFFECTIVE_DATA', @level2type = N'COLUMN', @level2name = N'MESSAGE_ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'主旨', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OFFICIAL_EMAIL_EFFECTIVE_DATA', @level2type = N'COLUMN', @level2name = N'SUBJECT';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'寄信者名稱', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OFFICIAL_EMAIL_EFFECTIVE_DATA', @level2type = N'COLUMN', @level2name = N'FROM_NAME';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'寄信者信箱', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OFFICIAL_EMAIL_EFFECTIVE_DATA', @level2type = N'COLUMN', @level2name = N'FROM_ADDRESS';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'內容', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OFFICIAL_EMAIL_EFFECTIVE_DATA', @level2type = N'COLUMN', @level2name = N'BODY';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'接收時間', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OFFICIAL_EMAIL_EFFECTIVE_DATA', @level2type = N'COLUMN', @level2name = N'RECEIVED_DATETIME';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'來源信件資料', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OFFICIAL_EMAIL_EFFECTIVE_DATA', @level2type = N'COLUMN', @level2name = N'FILE_PATH';

