CREATE TABLE [dbo].[PPCLIFE_EFFECTIVE_CASE_RELATIONSHIP] (
    [EFFEICTIVE_ID] INT       NOT NULL,
    [CASE_ID]       CHAR (14) NOT NULL,
    [ITEM_ID]       INT       NOT NULL,
    CONSTRAINT [PK_PPCLIFE_EFFECTIVE_CASE_RELATIONSHIP] PRIMARY KEY CLUSTERED ([EFFEICTIVE_ID] ASC, [CASE_ID] ASC, [ITEM_ID] ASC),
    CONSTRAINT [FK_PPCLIFE_EFFECTIVE_CASE_RELATIONSHIP_CASE_PPCLIFE] FOREIGN KEY ([CASE_ID], [ITEM_ID]) REFERENCES [dbo].[CASE_PPCLIFE] ([CASE_ID], [ITEM_ID]),
    CONSTRAINT [FK_PPCLIFE_EFFECTIVE_CASE_RELATIONSHIP_PPCLIFE_EFFECTIVE_SUMMARY] FOREIGN KEY ([EFFEICTIVE_ID]) REFERENCES [dbo].[PPCLIFE_EFFECTIVE_SUMMARY] ([ID])
);

