INSERT [OPTrade].[dbo].[ReportTradeActivityDetail_New] 
SELECT [TradeTime]
      ,[ActivityItemCode]
      ,[ActivityName]
      ,[LargeCategoryName]
      ,[SmallCategoryName]
      ,[ActivityID]
      ,[VoucherHeaderCode]
      ,[ItemName]
      ,[ItemCode]
      ,[DisplayCode]
      ,[BrandName]
      ,[VoucherType]
      ,[PerExchangePoint]
      ,[ExchangeQty]
      ,[mid]
      ,[TransactionID]
      ,CONVERT(varchar(4),[TradeTime],12)
      ,[VoucherHeaderItemCode]
      ,[ActivityItemName]
FROM [OPTrade].[dbo].[ReportTradeActivityDetail]