CREATE LOGIN [SMARTIIDBA]
    WITH PASSWORD = N'uabosgcsc5edpq|cu|pmhykhmsFT7_&#$!~<tskrqicfYc|v', SID = 0x82BFECDFE4ECA643B145486AE120BCCE, DEFAULT_DATABASE = [SMARTII0302], DEFAULT_LANGUAGE = [繁體中文], CHECK_POLICY = OFF;

