//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Resource.Tag {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Case_lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Case_lang() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMARTII.Resource.Tag.Case.lang", typeof(Case_lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-來源人資訊未輸入 的當地語系化字串。
        /// </summary>
        public static string _ {
            get {
                return ResourceManager.GetString("\'", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件已結案 的當地語系化字串。
        /// </summary>
        public static string CASE_ALREADY_FINISH {
            get {
                return ResourceManager.GetString("CASE_ALREADY_FINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-銷案狀態錯誤 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_CASE_TYPE_ERROR {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_CASE_TYPE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派案件(客服)-轉派客服銷案 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_CC_FINISH {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_CC_FINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派案件(客服)-轉派客服銷案失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_CC_FINISH_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_CC_FINISH_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派案件(客服)-轉派客服銷案成功 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_CC_FINISH_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_CC_FINISH_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-聯絡紀錄建立 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_COMMUNICATION {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_COMMUNICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-聯絡紀錄建立失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_COMMUNICATION_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_COMMUNICATION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得聯絡紀錄資料 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_COMMUNICATION_GET {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_COMMUNICATION_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得聯絡紀錄資料失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_COMMUNICATION_GET_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_COMMUNICATION_GET_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得聯絡紀錄資料成功 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_COMMUNICATION_GET_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_COMMUNICATION_GET_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-聯絡紀錄建立成功 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_COMMUNICATION_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_COMMUNICATION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派案件(總部、門市)-轉派總部、門市銷案 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_FINISH {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_FINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得轉派資料 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_GET {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派案件查詢(客服)-匯出 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_GET_EXCEL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_GET_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派案件查詢(客服)-匯出報表失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_GET_EXCEL_ERROR {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_GET_EXCEL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得轉派資料失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_GET_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_GET_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得轉派資料成功 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_GET_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_GET_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派案件查詢(客服)-查詢 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_GETLIST {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_GETLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派案件查詢(客服)-失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_GETLIST_ERROR {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_GETLIST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此轉派案件已被銷案 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_HAS_FINISH {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_HAS_FINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派案件查詢(總部、門市)-匯出 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_HS_GET_EXCEL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_HS_GET_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派案件查詢(總部、門市)-匯出報表失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_HS_GET_EXCEL_ERROR {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_HS_GET_EXCEL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派案件查詢(總部、門市)-查詢 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_HS_GETLIST {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_HS_GETLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派案件查詢(總部、門市)-失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_HS_GETLIST_ERROR {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_HS_GETLIST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得反應單資料 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_INVOICE_GET {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_INVOICE_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得反應單資料失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_INVOICE_GET_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_INVOICE_GET_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得反應單資料成功 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_INVOICE_GET_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_INVOICE_GET_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-重送反應單 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_INVOICE_RESEND {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_INVOICE_RESEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-重送反應單失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_INVOICE_RESEND_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_INVOICE_RESEND_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-重送反應單成功 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_INVOICE_RESEND_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_INVOICE_RESEND_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-開立反應單 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_INVOICE_SAVE {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_INVOICE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-開立反應單失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_INVOICE_SAVE_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_INVOICE_SAVE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-開立反應單成功 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_INVOICE_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_INVOICE_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-寄出反應單 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_INVOICE_SEND {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_INVOICE_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-寄出反應單失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_INVOICE_SEND_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_INVOICE_SEND_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-寄出反應單成功 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_INVOICE_SEND_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_INVOICE_SEND_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-更新反應單 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_INVOICE_UPDATE {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_INVOICE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-更新反應單失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_INVOICE_UPDATE_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_INVOICE_UPDATE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-更新反應單成功 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_INVOICE_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_INVOICE_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-轉派並未完全結束 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_NOT_ALL_CLOSED {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_NOT_ALL_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得一般通知資料 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_NOTICE_GET {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_NOTICE_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得一般通知資料失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_NOTICE_GET_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_NOTICE_GET_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得一般通知資料成功 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_NOTICE_GET_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_NOTICE_GET_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-一般通知建立 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_NOTICE_SAVE {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_NOTICE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-一般通知建立失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_NOTICE_SAVE_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_NOTICE_SAVE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-一般通知建立成功 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_NOTICE_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_NOTICE_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-一般通知更新 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_NOTICE_UPDATE {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_NOTICE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-一般通知更新失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_NOTICE_UPDATE_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_NOTICE_UPDATE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-一般通知更新成功 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_NOTICE_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_NOTICE_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派案件(總部、門市)-轉派資料重填 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_REFILL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_REFILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派案件(客服)-轉派銷案駁回 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_REJECT {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_REJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派案件(客服)-轉派銷案駁回失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_REJECT_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_REJECT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派案件(客服)-轉派銷案駁回成功 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_REJECT_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_REJECT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派案件(總部、門市)-轉派回覆 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_REPLY {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_REPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-轉派立案 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_SAVE {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-轉派立案失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_SAVE_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_SAVE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-轉派立案成功 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-駁回時狀態須為結案 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_TYPE_ERROR_WHEN_REJECT {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_TYPE_ERROR_WHEN_REJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-轉派更新 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_UPDATE {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-轉派更新失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_UPDATE_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_UPDATE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-轉派更新成功 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派案件查詢(廠商)-匯出 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_VENDOR_GET_EXCEL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_VENDOR_GET_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派案件查詢(廠商)-匯出報表失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_VENDOR_GET_EXCEL_ERROR {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_VENDOR_GET_EXCEL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派案件查詢(廠商)-查詢 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_VENDOR_GETLIST {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_VENDOR_GETLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派案件查詢(廠商)-失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_VENDOR_GETLIST_ERROR {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_VENDOR_GETLIST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件查詢(客服)-匯出 的當地語系化字串。
        /// </summary>
        public static string CASE_CALLCENTER_GET_EXCEL {
            get {
                return ResourceManager.GetString("CASE_CALLCENTER_GET_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件查詢(客服)-匯出報表失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_CALLCENTER_GET_EXCEL_ERROR {
            get {
                return ResourceManager.GetString("CASE_CALLCENTER_GET_EXCEL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件查詢(客服)-查詢 的當地語系化字串。
        /// </summary>
        public static string CASE_CALLCENTER_GETLIST {
            get {
                return ResourceManager.GetString("CASE_CALLCENTER_GETLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件查詢(客服)-查詢失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_CALLCENTER_GETLIST_ERROR {
            get {
                return ResourceManager.GetString("CASE_CALLCENTER_GETLIST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件查詢(總部、門市)-匯出 的當地語系化字串。
        /// </summary>
        public static string CASE_CALLCENTER_HS_GET_EXCEL {
            get {
                return ResourceManager.GetString("CASE_CALLCENTER_HS_GET_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件查詢(總部、門市)-匯出報表失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_CALLCENTER_HS_GET_EXCEL_ERROR {
            get {
                return ResourceManager.GetString("CASE_CALLCENTER_HS_GET_EXCEL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件查詢(總部、門市)-查詢 的當地語系化字串。
        /// </summary>
        public static string CASE_CALLCENTER_HS_GETLIST {
            get {
                return ResourceManager.GetString("CASE_CALLCENTER_HS_GETLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件查詢(總部、門市)-查詢失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_CALLCENTER_HS_GETLIST_ERROR {
            get {
                return ResourceManager.GetString("CASE_CALLCENTER_HS_GETLIST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-檢核案件有效性 的當地語系化字串。
        /// </summary>
        public static string CASE_CHECK {
            get {
                return ResourceManager.GetString("CASE_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-檢核案件有效性失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_CHECK_FAIL {
            get {
                return ResourceManager.GetString("CASE_CHECK_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-檢核案件有效性成功 的當地語系化字串。
        /// </summary>
        public static string CASE_CHECK_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_CHECK_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-驗證勾稽案件是否存在 的當地語系化字串。
        /// </summary>
        public static string CASE_CHECKCASE {
            get {
                return ResourceManager.GetString("CASE_CHECKCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-驗證勾稽案件是否存在失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_CHECKCASE_FAIL {
            get {
                return ResourceManager.GetString("CASE_CHECKCASE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-驗證勾稽案件是否存在成功 的當地語系化字串。
        /// </summary>
        public static string CASE_CHECKCASE_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_CHECKCASE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-被反應者至少要有權責單位 的當地語系化字串。
        /// </summary>
        public static string CASE_COMPLAINTED_USER_AT_LEAST_ONE_RESPONSEBLILITY {
            get {
                return ResourceManager.GetString("CASE_COMPLAINTED_USER_AT_LEAST_ONE_RESPONSEBLILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-案件結案 的當地語系化字串。
        /// </summary>
        public static string CASE_FINISH {
            get {
                return ResourceManager.GetString("CASE_FINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-請輸入結案內容 的當地語系化字串。
        /// </summary>
        public static string CASE_FINISH_CONTENT_FAIL {
            get {
                return ResourceManager.GetString("CASE_FINISH_CONTENT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-個人結案時使用者代號不吻合 的當地語系化字串。
        /// </summary>
        public static string CASE_FINISH_ERROR_USER_NOT_MATCH_ID {
            get {
                return ResourceManager.GetString("CASE_FINISH_ERROR_USER_NOT_MATCH_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-案件結案失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_FINISH_FAIL {
            get {
                return ResourceManager.GetString("CASE_FINISH_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-此結案資訊必須至少勾選一種 的當地語系化字串。
        /// </summary>
        public static string CASE_FINISH_REASON_CLASSIFICATION_FAIL {
            get {
                return ResourceManager.GetString("CASE_FINISH_REASON_CLASSIFICATION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-案件結案成功 的當地語系化字串。
        /// </summary>
        public static string CASE_FINISH_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_FINISH_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-結案案件回信 的當地語系化字串。
        /// </summary>
        public static string CASE_FINISHEDMAILREPLY {
            get {
                return ResourceManager.GetString("CASE_FINISHEDMAILREPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-結案案件回信失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_FINISHEDMAILREPLY_FAIL {
            get {
                return ResourceManager.GetString("CASE_FINISHEDMAILREPLY_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-結案案件回信成功 的當地語系化字串。
        /// </summary>
        public static string CASE_FINISHEDMAILREPLY_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_FINISHEDMAILREPLY_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得案件 的當地語系化字串。
        /// </summary>
        public static string CASE_GET {
            get {
                return ResourceManager.GetString("CASE_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得歷程列表 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_ASSIGNMENT_AGGREGATE {
            get {
                return ResourceManager.GetString("CASE_GET_ASSIGNMENT_AGGREGATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得歷程列表成功 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_ASSIGNMENT_AGGREGATE_FAIL {
            get {
                return ResourceManager.GetString("CASE_GET_ASSIGNMENT_AGGREGATE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得歷程列表失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_ASSIGNMENT_AGGREGATE_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_GET_ASSIGNMENT_AGGREGATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得歷程清單 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_ASSIGNMENT_RESUME {
            get {
                return ResourceManager.GetString("CASE_GET_ASSIGNMENT_RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得歷程清單失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_ASSIGNMENT_RESUME_FAIL {
            get {
                return ResourceManager.GetString("CASE_GET_ASSIGNMENT_RESUME_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得歷程清單成功 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_ASSIGNMENT_RESUME_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_GET_ASSIGNMENT_RESUME_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得案件資料 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_CASE {
            get {
                return ResourceManager.GetString("CASE_GET_CASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得案件資料失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_CASE_FAIL {
            get {
                return ResourceManager.GetString("CASE_GET_CASE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得案件編號清單 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_CASE_IDs {
            get {
                return ResourceManager.GetString("CASE_GET_CASE_IDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得案件編號清單失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_CASE_IDs_FAIL {
            get {
                return ResourceManager.GetString("CASE_GET_CASE_IDs_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得案件編號清單成功 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_CASE_IDs_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_GET_CASE_IDs_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得案件資料成功 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_CASE_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_GET_CASE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得案件失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_FAIL {
            get {
                return ResourceManager.GetString("CASE_GET_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得未結案件清單 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_NEARLY_LIST {
            get {
                return ResourceManager.GetString("CASE_GET_NEARLY_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得未結案件清單成功 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_NEARLY_LIST_FAIL {
            get {
                return ResourceManager.GetString("CASE_GET_NEARLY_LIST_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得未結案件清單失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_NEARLY_LIST_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_GET_NEARLY_LIST_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得預立案件清單 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_PREVENT_LIST {
            get {
                return ResourceManager.GetString("CASE_GET_PREVENT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得預立案件清單失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_PREVENT_LIST_FAIL {
            get {
                return ResourceManager.GetString("CASE_GET_PREVENT_LIST_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得預立案件清單成功 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_PREVENT_LIST_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_GET_PREVENT_LIST_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得流程引導 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_QUESTIONCLASSIFICATIONGUIDE {
            get {
                return ResourceManager.GetString("CASE_GET_QUESTIONCLASSIFICATIONGUIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得流程引導失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_QUESTIONCLASSIFICATIONGUIDE_FAIL {
            get {
                return ResourceManager.GetString("CASE_GET_QUESTIONCLASSIFICATIONGUIDE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得流程引導成功 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_QUESTIONCLASSIFICATIONGUIDE_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_GET_QUESTIONCLASSIFICATIONGUIDE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得案件追蹤 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_REMINDFROMCASEPAGE {
            get {
                return ResourceManager.GetString("CASE_GET_REMINDFROMCASEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得案件來源 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_SOURCE {
            get {
                return ResourceManager.GetString("CASE_GET_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得案件來源成功 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_SOURCE_FAIL {
            get {
                return ResourceManager.GetString("CASE_GET_SOURCE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得案件來源失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_SOURCE_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_GET_SOURCE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得案件成功 的當地語系化字串。
        /// </summary>
        public static string CASE_GET_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_GET_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得案件轉派清單 的當地語系化字串。
        /// </summary>
        public static string CASE_GETLIST_ASSIGNMENT {
            get {
                return ResourceManager.GetString("CASE_GETLIST_ASSIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得案件轉派清單失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_GETLIST_ASSIGNMENT_FAIL {
            get {
                return ResourceManager.GetString("CASE_GETLIST_ASSIGNMENT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得案件轉派清單成功 的當地語系化字串。
        /// </summary>
        public static string CASE_GETLIST_ASSIGNMENT_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_GETLIST_ASSIGNMENT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得快速結案原因清單 的當地語系化字串。
        /// </summary>
        public static string CASE_GETLIST_FASTFINISHEDREASON {
            get {
                return ResourceManager.GetString("CASE_GETLIST_FASTFINISHEDREASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得快速結案原因清單失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_GETLIST_FASTFINISHEDREASON_FAIL {
            get {
                return ResourceManager.GetString("CASE_GETLIST_FASTFINISHEDREASON_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得快速結案原因清單成功 的當地語系化字串。
        /// </summary>
        public static string CASE_GETLIST_FASTFINISHEDREASON_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_GETLIST_FASTFINISHEDREASON_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得歷程回應 的當地語系化字串。
        /// </summary>
        public static string CASE_GETRESUMES {
            get {
                return ResourceManager.GetString("CASE_GETRESUMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得歷程回應失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_GETRESUMES_FAIL {
            get {
                return ResourceManager.GetString("CASE_GETRESUMES_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得歷程回應成功 的當地語系化字串。
        /// </summary>
        public static string CASE_GETRESUMES_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_GETRESUMES_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-該Group並無服務此企業別 的當地語系化字串。
        /// </summary>
        public static string CASE_GROUP_NO_BU {
            get {
                return ResourceManager.GetString("CASE_GROUP_NO_BU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-銷案案件 (廠商/門市) 的當地語系化字串。
        /// </summary>
        public static string CASE_HS_VENDOR_FINISH {
            get {
                return ResourceManager.GetString("CASE_HS_VENDOR_FINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-銷案案件 (廠商/門市)失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_HS_VENDOR_FINISH_FAIL {
            get {
                return ResourceManager.GetString("CASE_HS_VENDOR_FINISH_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-銷案案件 (廠商/門市)成功 的當地語系化字串。
        /// </summary>
        public static string CASE_HS_VENDOR_FINISH_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_HS_VENDOR_FINISH_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-資料重填 (廠商/門市) 的當地語系化字串。
        /// </summary>
        public static string CASE_HS_VENDOR_SAVEREFILL {
            get {
                return ResourceManager.GetString("CASE_HS_VENDOR_SAVEREFILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-資料重填 (廠商/門市)失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_HS_VENDOR_SAVEREFILL_FAIL {
            get {
                return ResourceManager.GetString("CASE_HS_VENDOR_SAVEREFILL_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-資料重填 (廠商/門市)成功 的當地語系化字串。
        /// </summary>
        public static string CASE_HS_VENDOR_SAVEREFILL_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_HS_VENDOR_SAVEREFILL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 反應單取消 的當地語系化字串。
        /// </summary>
        public static string CASE_INVOICE_CANCEL {
            get {
                return ResourceManager.GetString("CASE_INVOICE_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 反應單取消失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_INVOICE_CANCEL_FAIL {
            get {
                return ResourceManager.GetString("CASE_INVOICE_CANCEL_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-請輸入商品資訊 的當地語系化字串。
        /// </summary>
        public static string CASE_ITEM_REQUIRED {
            get {
                return ResourceManager.GetString("CASE_ITEM_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-無轉派資料 的當地語系化字串。
        /// </summary>
        public static string CASE_NO_ASSIGNMENT {
            get {
                return ResourceManager.GetString("CASE_NO_ASSIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-並無該執行單位的權限 的當地語系化字串。
        /// </summary>
        public static string CASE_NO_GROUP_AUTH {
            get {
                return ResourceManager.GetString("CASE_NO_GROUP_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-不允許多個反應單開立 的當地語系化字串。
        /// </summary>
        public static string CASE_NO_MUTIPLE_ASSIGN_TICKET {
            get {
                return ResourceManager.GetString("CASE_NO_MUTIPLE_ASSIGN_TICKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-並未傳入操作人員組織代號 的當地語系化字串。
        /// </summary>
        public static string CASE_NO_PASS_EDITOR_NODE_JOB_ID {
            get {
                return ResourceManager.GetString("CASE_NO_PASS_EDITOR_NODE_JOB_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-駁回時未輸入型態 的當地語系化字串。
        /// </summary>
        public static string CASE_NO_REJECT_TYPE {
            get {
                return ResourceManager.GetString("CASE_NO_REJECT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-找不到企業代號三碼 的當地語系化字串。
        /// </summary>
        public static string CASE_NODE_KEY_UNDEFIND {
            get {
                return ResourceManager.GetString("CASE_NODE_KEY_UNDEFIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-檢視反應單 的當地語系化字串。
        /// </summary>
        public static string CASE_PREVIEW_INVOICE {
            get {
                return ResourceManager.GetString("CASE_PREVIEW_INVOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-檢視反應單失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_PREVIEW_INVOICE_FAIL {
            get {
                return ResourceManager.GetString("CASE_PREVIEW_INVOICE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-檢視反應單成功 的當地語系化字串。
        /// </summary>
        public static string CASE_PREVIEW_INVOICE_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_PREVIEW_INVOICE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-立案 的當地語系化字串。
        /// </summary>
        public static string CASE_SAVE {
            get {
                return ResourceManager.GetString("CASE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-立案失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_SAVE_FAIL {
            get {
                return ResourceManager.GetString("CASE_SAVE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-立案成功 的當地語系化字串。
        /// </summary>
        public static string CASE_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-案件來源不能為預立案 的當地語系化字串。
        /// </summary>
        public static string CASE_SOURCE_IS_REVENTION_UNDEFIND {
            get {
                return ResourceManager.GetString("CASE_SOURCE_IS_REVENTION_UNDEFIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此案件編號不存在: {0} 的當地語系化字串。
        /// </summary>
        public static string CASE_SOURCE_RELATE_NOEXIST {
            get {
                return ResourceManager.GetString("CASE_SOURCE_RELATE_NOEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不可跨企業別勾稽 的當地語系化字串。
        /// </summary>
        public static string CASE_SOURCE_RELATE_NOT_SAME_BU {
            get {
                return ResourceManager.GetString("CASE_SOURCE_RELATE_NOT_SAME_BU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此案編已為該來源底下案件 的當地語系化字串。
        /// </summary>
        public static string CASE_SOURCE_RELATE_SOURCE_REPEAT {
            get {
                return ResourceManager.GetString("CASE_SOURCE_RELATE_SOURCE_REPEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-建立來源 的當地語系化字串。
        /// </summary>
        public static string CASE_SOURCE_SAVE {
            get {
                return ResourceManager.GetString("CASE_SOURCE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-建立來源包含案件 的當地語系化字串。
        /// </summary>
        public static string CASE_SOURCE_SAVE_COMPLETE {
            get {
                return ResourceManager.GetString("CASE_SOURCE_SAVE_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-建立來源包含案件失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_SOURCE_SAVE_COMPLETE_FAIL {
            get {
                return ResourceManager.GetString("CASE_SOURCE_SAVE_COMPLETE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-建立來源包含案件成功 的當地語系化字串。
        /// </summary>
        public static string CASE_SOURCE_SAVE_COMPLETE_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_SOURCE_SAVE_COMPLETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-建立來源失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_SOURCE_SAVE_FAIL {
            get {
                return ResourceManager.GetString("CASE_SOURCE_SAVE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-建立來源成功 的當地語系化字串。
        /// </summary>
        public static string CASE_SOURCE_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_SOURCE_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-案件來源不存在 的當地語系化字串。
        /// </summary>
        public static string CASE_SOURCE_UNDEFIND {
            get {
                return ResourceManager.GetString("CASE_SOURCE_UNDEFIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件來源-更新 的當地語系化字串。
        /// </summary>
        public static string CASE_SOURCE_UPDATE {
            get {
                return ResourceManager.GetString("CASE_SOURCE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件來源-更新成功 的當地語系化字串。
        /// </summary>
        public static string CASE_SOURCE_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_SOURCE_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件來源-更新失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_SOURCE_UPDTAE_FAIL {
            get {
                return ResourceManager.GetString("CASE_SOURCE_UPDTAE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-反應者不得為空 的當地語系化字串。
        /// </summary>
        public static string CASE_SOURCE_USER_UNDEFIND {
            get {
                return ResourceManager.GetString("CASE_SOURCE_USER_UNDEFIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-建立來源(包含案件) 的當地語系化字串。
        /// </summary>
        public static string CASE_SOURCECOMPLETE_SAVE {
            get {
                return ResourceManager.GetString("CASE_SOURCECOMPLETE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-建立來源(包含案件)失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_SOURCECOMPLETE_SAVE_FAIL {
            get {
                return ResourceManager.GetString("CASE_SOURCECOMPLETE_SAVE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-建立來源(包含案件)成功 的當地語系化字串。
        /// </summary>
        public static string CASE_SOURCECOMPLETE_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_SOURCECOMPLETE_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} ，此案件標籤已存在(已停用) 的當地語系化字串。
        /// </summary>
        public static string CASE_TAG_NAME_REPEAT {
            get {
                return ResourceManager.GetString("CASE_TAG_NAME_REPEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-不允許多個反應單開立 的當地語系化字串。
        /// </summary>
        public static string CASE_TICKET_OUT_OF_INDEX {
            get {
                return ResourceManager.GetString("CASE_TICKET_OUT_OF_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-案件狀態錯誤 的當地語系化字串。
        /// </summary>
        public static string CASE_TYPE_ERROR {
            get {
                return ResourceManager.GetString("CASE_TYPE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-案件不存在 的當地語系化字串。
        /// </summary>
        public static string CASE_UNDEFIND {
            get {
                return ResourceManager.GetString("CASE_UNDEFIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-案件解鎖 的當地語系化字串。
        /// </summary>
        public static string CASE_UNLOCK {
            get {
                return ResourceManager.GetString("CASE_UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-案件解鎖失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_UNLOCK_FAIL {
            get {
                return ResourceManager.GetString("CASE_UNLOCK_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-案件解鎖成功 的當地語系化字串。
        /// </summary>
        public static string CASE_UNLOCK_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_UNLOCK_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-案件更新 的當地語系化字串。
        /// </summary>
        public static string CASE_UPDATE {
            get {
                return ResourceManager.GetString("CASE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-案件更新失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_UPDATE_FAIL {
            get {
                return ResourceManager.GetString("CASE_UPDATE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-案件更新成功 的當地語系化字串。
        /// </summary>
        public static string CASE_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得來源 的當地語系化字串。
        /// </summary>
        public static string GET_SOURCE_NATIVE {
            get {
                return ResourceManager.GetString("GET_SOURCE_NATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得來源失敗 的當地語系化字串。
        /// </summary>
        public static string GET_SOURCE_NATIVE_FAIL {
            get {
                return ResourceManager.GetString("GET_SOURCE_NATIVE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件管理-取得來源成功 的當地語系化字串。
        /// </summary>
        public static string GET_SOURCE_NATIVE_SUCCESS {
            get {
                return ResourceManager.GetString("GET_SOURCE_NATIVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該案件來源已開啟: {0} 的當地語系化字串。
        /// </summary>
        public static string GET_SOURCE_REPEAT {
            get {
                return ResourceManager.GetString("GET_SOURCE_REPEAT", resourceCulture);
            }
        }
    }
}
