//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Resource.Tag {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CaseAssignGroup_lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CaseAssignGroup_lang() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMARTII.Resource.Tag.CaseAssignGroup.lang", typeof(CaseAssignGroup_lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 派工群組-找不到既有單位 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGN_GROUP_BU_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGN_GROUP_BU_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 派工群組-新增 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGN_GROUP_CREATE {
            get {
                return ResourceManager.GetString("CASE_ASSIGN_GROUP_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 派工群組-新增 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGN_GROUP_CREATE_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGN_GROUP_CREATE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 派工群組-新增成功 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGN_GROUP_CREATE_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_ASSIGN_GROUP_CREATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 派工群組-刪除 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGN_GROUP_DELETE {
            get {
                return ResourceManager.GetString("CASE_ASSIGN_GROUP_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 派工群組-刪除失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGN_GROUP_DELETE_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGN_GROUP_DELETE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 派工群組-批次刪除 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGN_GROUP_DELETE_RANGE {
            get {
                return ResourceManager.GetString("CASE_ASSIGN_GROUP_DELETE_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 派工群組-批次刪除失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGN_GROUP_DELETE_RANGE_FAILED {
            get {
                return ResourceManager.GetString("CASE_ASSIGN_GROUP_DELETE_RANGE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 派工群組-批次刪除成功 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGN_GROUP_DELETE_RANGE_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_ASSIGN_GROUP_DELETE_RANGE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 派工群組-刪除成功 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGN_GROUP_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_ASSIGN_GROUP_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 派工群組-群組名稱重複 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGN_GROUP_DUPLICATE_NAME {
            get {
                return ResourceManager.GetString("CASE_ASSIGN_GROUP_DUPLICATE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 派工群組-取得 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGN_GROUP_GET {
            get {
                return ResourceManager.GetString("CASE_ASSIGN_GROUP_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 派工群組-取得失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGN_GROUP_GET_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGN_GROUP_GET_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 派工群組-取得清單 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGN_GROUP_GETLIST {
            get {
                return ResourceManager.GetString("CASE_ASSIGN_GROUP_GETLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 派工群組-取得清單失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGN_GROUP_GETLIST_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGN_GROUP_GETLIST_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 派工群組-更新 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGN_GROUP_UPDATE {
            get {
                return ResourceManager.GetString("CASE_ASSIGN_GROUP_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 派工群組-更新失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGN_GROUP_UPDATE_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGN_GROUP_UPDATE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 派工群組-更新成功 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGN_GROUP_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("CASE_ASSIGN_GROUP_UPDATE_SUCCESS", resourceCulture);
            }
        }
    }
}
