//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Resource.Tag {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common_lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common_lang() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMARTII.Resource.Tag.Common.lang", typeof(Common_lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者帳號重複 的當地語系化字串。
        /// </summary>
        public static string ACCOUNT_EXIST {
            get {
                return ResourceManager.GetString("ACCOUNT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AD 人員不支援變更密碼 的當地語系化字串。
        /// </summary>
        public static string AD_DENY_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("AD_DENY_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AD使用者不存在 的當地語系化字串。
        /// </summary>
        public static string AD_USER_NULL {
            get {
                return ResourceManager.GetString("AD_USER_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 權杖不合法 的當地語系化字串。
        /// </summary>
        public static string AUTH_TOKEN_INVALID {
            get {
                return ResourceManager.GetString("AUTH_TOKEN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認證過期 的當地語系化字串。
        /// </summary>
        public static string AUTH_TOKEN_TIMOUT {
            get {
                return ResourceManager.GetString("AUTH_TOKEN_TIMOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 對應方式不存在 的當地語系化字串。
        /// </summary>
        public static string AUTO_MAPPER_NULL {
            get {
                return ResourceManager.GetString("AUTO_MAPPER_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 企業別未設置時效 的當地語系化字串。
        /// </summary>
        public static string BUSINESSS_CASE_WARNING_NOT_FOUND {
            get {
                return ResourceManager.GetString("BUSINESSS_CASE_WARNING_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 企業別取得失敗 的當地語系化字串。
        /// </summary>
        public static string BUSINESSS_NOT_FOUND {
            get {
                return ResourceManager.GetString("BUSINESSS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 必須填寫被反應者資訊 的當地語系化字串。
        /// </summary>
        public static string COMPLAINEDUSERS_ERROR {
            get {
                return ResourceManager.GetString("COMPLAINEDUSERS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除失敗 , 回傳註記為 【FALSE】 可能沒有找到對應資料或是其他原因。 的當地語系化字串。
        /// </summary>
        public static string DATABASE_DELETE_ERROR {
            get {
                return ResourceManager.GetString("DATABASE_DELETE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寄件人不得為空 的當地語系化字串。
        /// </summary>
        public static string EMAIL_SENDER_NOT_ALLOW_NULL {
            get {
                return ResourceManager.GetString("EMAIL_SENDER_NOT_ALLOW_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 首次登入，請變更密碼 的當地語系化字串。
        /// </summary>
        public static string FIRST_LOGIN {
            get {
                return ResourceManager.GetString("FIRST_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得資料失敗 的當地語系化字串。
        /// </summary>
        public static string GET_DATA_FAIL {
            get {
                return ResourceManager.GetString("GET_DATA_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GROUP取得失敗 的當地語系化字串。
        /// </summary>
        public static string GROUP_NOT_FOUND {
            get {
                return ResourceManager.GetString("GROUP_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商品資訊未啟用 的當地語系化字串。
        /// </summary>
        public static string ITEM_NOT_ENABLE {
            get {
                return ResourceManager.GetString("ITEM_NOT_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 傳入物件驗證失敗 的當地語系化字串。
        /// </summary>
        public static string MODEL_INVALID {
            get {
                return ResourceManager.GetString("MODEL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 超過三個月未變更密碼，請變更 的當地語系化字串。
        /// </summary>
        public static string MONTH_TIMEOUT_LOGIN {
            get {
                return ResourceManager.GetString("MONTH_TIMEOUT_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼不可等於帳號 的當地語系化字串。
        /// </summary>
        public static string NEWPASSWORD_EQUAL_ACCOUNT {
            get {
                return ResourceManager.GetString("NEWPASSWORD_EQUAL_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新密碼不能等同於舊密碼 的當地語系化字串。
        /// </summary>
        public static string NEWPASSWORD_EQUAL_OLDPASSWORD {
            get {
                return ResourceManager.GetString("NEWPASSWORD_EQUAL_OLDPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新密碼與過去五組密碼相同，請重新輸入 的當地語系化字串。
        /// </summary>
        public static string NEWPASSWORD_INSIDE_FIVE_GROUPS {
            get {
                return ResourceManager.GetString("NEWPASSWORD_INSIDE_FIVE_GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 沒有傳入驗證資訊 的當地語系化字串。
        /// </summary>
        public static string NO_AUTH_HEADER {
            get {
                return ResourceManager.GetString("NO_AUTH_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 沒有傳入驗證資訊 的當地語系化字串。
        /// </summary>
        public static string NO_AUTH_HEADER_TOKEN {
            get {
                return ResourceManager.GetString("NO_AUTH_HEADER_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無 的當地語系化字串。
        /// </summary>
        public static string NONE {
            get {
                return ResourceManager.GetString("NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 外部網站不允許使用AD登入 的當地語系化字串。
        /// </summary>
        public static string NOT_ALLOW_EXTRANET_LOGIN {
            get {
                return ResourceManager.GetString("NOT_ALLOW_EXTRANET_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 找不到資料 的當地語系化字串。
        /// </summary>
        public static string NOT_FOUND_DATA {
            get {
                return ResourceManager.GetString("NOT_FOUND_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不是系統使用者 的當地語系化字串。
        /// </summary>
        public static string NOT_SYSTEM_USER {
            get {
                return ResourceManager.GetString("NOT_SYSTEM_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 原密碼入錯誤 的當地語系化字串。
        /// </summary>
        public static string OLDPASSWORD_ERROR {
            get {
                return ResourceManager.GetString("OLDPASSWORD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數不得為空 的當地語系化字串。
        /// </summary>
        public static string PARAMETER_NULL {
            get {
                return ResourceManager.GetString("PARAMETER_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼不得為空 的當地語系化字串。
        /// </summary>
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼錯誤 的當地語系化字串。
        /// </summary>
        public static string PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 問題分類未啟用 的當地語系化字串。
        /// </summary>
        public static string QUESTION_CLASSIFICATION_NOT_ENABLE {
            get {
                return ResourceManager.GetString("QUESTION_CLASSIFICATION_NOT_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 問題分類名稱重複 的當地語系化字串。
        /// </summary>
        public static string QUESTIONCLASSIFICATION_NAME_DUPLICATE {
            get {
                return ResourceManager.GetString("QUESTIONCLASSIFICATION_NAME_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發生錯誤!! 查無案件資訊 的當地語系化字串。
        /// </summary>
        public static string REPORT_ERROR {
            get {
                return ResourceManager.GetString("REPORT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未選取組織定義 的當地語系化字串。
        /// </summary>
        public static string UNCHOOSE_DEFIN_TREE {
            get {
                return ResourceManager.GetString("UNCHOOSE_DEFIN_TREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者帳號不得為空 的當地語系化字串。
        /// </summary>
        public static string USER_ACCOUNT_NULL {
            get {
                return ResourceManager.GetString("USER_ACCOUNT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者始末日期未輸入 的當地語系化字串。
        /// </summary>
        public static string USER_ACTIVEDATE_ERROR {
            get {
                return ResourceManager.GetString("USER_ACTIVEDATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號停用，請洽系統管理員 的當地語系化字串。
        /// </summary>
        public static string USER_DISABLED {
            get {
                return ResourceManager.GetString("USER_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者重複 的當地語系化字串。
        /// </summary>
        public static string USER_DUPLICATE {
            get {
                return ResourceManager.GetString("USER_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號異常 的當地語系化字串。
        /// </summary>
        public static string USER_EXCEPTION {
            get {
                return ResourceManager.GetString("USER_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者已鎖定，請洽系統管理員 的當地語系化字串。
        /// </summary>
        public static string USER_LOCK {
            get {
                return ResourceManager.GetString("USER_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號密碼錯誤 的當地語系化字串。
        /// </summary>
        public static string USER_LOGIN_ERROR {
            get {
                return ResourceManager.GetString("USER_LOGIN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選取人員無該執行單位的權限 的當地語系化字串。
        /// </summary>
        public static string USER_NOT_SERVICE {
            get {
                return ResourceManager.GetString("USER_NOT_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者未啟用 的當地語系化字串。
        /// </summary>
        public static string USER_UNACTIVE {
            get {
                return ResourceManager.GetString("USER_UNACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 找不到使用者 的當地語系化字串。
        /// </summary>
        public static string USER_UNDEFIND {
            get {
                return ResourceManager.GetString("USER_UNDEFIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼強度不合法 的當地語系化字串。
        /// </summary>
        public static string VALID_PASSWORD_STRENGTH_FAIL {
            get {
                return ResourceManager.GetString("VALID_PASSWORD_STRENGTH_FAIL", resourceCulture);
            }
        }
    }
}
