//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Resource.Tag {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HeaderQuarterNode_lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HeaderQuarterNode_lang() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMARTII.Resource.Tag.HeaderQuarterNode.lang", typeof(HeaderQuarterNode_lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-新增職稱 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_ADD_JOB {
            get {
                return ResourceManager.GetString("HEADERQUARTER_ADD_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-新增職稱失敗 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_ADD_JOB_FAIL {
            get {
                return ResourceManager.GetString("HEADERQUARTER_ADD_JOB_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-新增職稱成功 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_ADD_JOB_SUCCESS {
            get {
                return ResourceManager.GetString("HEADERQUARTER_ADD_JOB_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-新增人員 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_ADD_USER {
            get {
                return ResourceManager.GetString("HEADERQUARTER_ADD_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-新增人員失敗 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_ADD_USER_FAIL {
            get {
                return ResourceManager.GetString("HEADERQUARTER_ADD_USER_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-新增人員成功 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_ADD_USER_SUCCESS {
            get {
                return ResourceManager.GetString("HEADERQUARTER_ADD_USER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-刪除職稱 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_DELETE_JOB {
            get {
                return ResourceManager.GetString("HEADERQUARTER_DELETE_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-刪除職稱失敗 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_DELETE_JOB_FAIL {
            get {
                return ResourceManager.GetString("HEADERQUARTER_DELETE_JOB_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-刪除職稱成功 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_DELETE_JOB_SUCCESS {
            get {
                return ResourceManager.GetString("HEADERQUARTER_DELETE_JOB_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-刪除人員 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_DELETE_USER {
            get {
                return ResourceManager.GetString("HEADERQUARTER_DELETE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-刪除人員失敗 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_DELETE_USER_FAIL {
            get {
                return ResourceManager.GetString("HEADERQUARTER_DELETE_USER_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-刪除人員成功 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_DELETE_USER_SUCCESS {
            get {
                return ResourceManager.GetString("HEADERQUARTER_DELETE_USER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該節點或底下節點還有未結案的案件，無法停用 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_DISABLE_ERROR {
            get {
                return ResourceManager.GetString("HEADERQUARTER_DISABLE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-新增 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_NODE_CREATE {
            get {
                return ResourceManager.GetString("HEADERQUARTER_NODE_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-新增失敗 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_NODE_CREATE_FAIL {
            get {
                return ResourceManager.GetString("HEADERQUARTER_NODE_CREATE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-新增成功 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_NODE_CREATE_SUCCESS {
            get {
                return ResourceManager.GetString("HEADERQUARTER_NODE_CREATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-停用 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_NODE_DISABLE {
            get {
                return ResourceManager.GetString("HEADERQUARTER_NODE_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-停用失敗 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_NODE_DISABLE_FAIL {
            get {
                return ResourceManager.GetString("HEADERQUARTER_NODE_DISABLE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-停用成功 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_NODE_DISABLE_SUCCESS {
            get {
                return ResourceManager.GetString("HEADERQUARTER_NODE_DISABLE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-取得 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_NODE_GET {
            get {
                return ResourceManager.GetString("HEADERQUARTER_NODE_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-取得全部 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_NODE_GET_ALL {
            get {
                return ResourceManager.GetString("HEADERQUARTER_NODE_GET_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-取得全部成功 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_NODE_GET_ALL_FAIL {
            get {
                return ResourceManager.GetString("HEADERQUARTER_NODE_GET_ALL_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-取得全部失敗 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_NODE_GET_ALL_SUCCESS {
            get {
                return ResourceManager.GetString("HEADERQUARTER_NODE_GET_ALL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-取得失敗 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_NODE_GET_FAIL {
            get {
                return ResourceManager.GetString("HEADERQUARTER_NODE_GET_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-取得樹組 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_NODE_GET_NESTED {
            get {
                return ResourceManager.GetString("HEADERQUARTER_NODE_GET_NESTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-取得樹組失敗 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_NODE_GET_NESTED_FAIL {
            get {
                return ResourceManager.GetString("HEADERQUARTER_NODE_GET_NESTED_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-取得樹組成功 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_NODE_GET_NESTED_SUCCESS {
            get {
                return ResourceManager.GetString("HEADERQUARTER_NODE_GET_NESTED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-取得成功 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_NODE_GET_SUCCESS {
            get {
                return ResourceManager.GetString("HEADERQUARTER_NODE_GET_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-企業別代碼已重複 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_NODE_KEY_ERROR {
            get {
                return ResourceManager.GetString("HEADERQUARTER_NODE_KEY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-更新 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_NODE_UPDATE {
            get {
                return ResourceManager.GetString("HEADERQUARTER_NODE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-更新失敗 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_NODE_UPDATE_FAIL {
            get {
                return ResourceManager.GetString("HEADERQUARTER_NODE_UPDATE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-更新成功 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_NODE_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("HEADERQUARTER_NODE_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-門市店號已重複 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_STORE_CODE_ERROR {
            get {
                return ResourceManager.GetString("HEADERQUARTER_STORE_CODE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-更新樹 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_UPDATE_TREE {
            get {
                return ResourceManager.GetString("HEADERQUARTER_UPDATE_TREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-更新樹失敗 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_UPDATE_TREE_FAIL {
            get {
                return ResourceManager.GetString("HEADERQUARTER_UPDATE_TREE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總部組織-更新樹成功 的當地語系化字串。
        /// </summary>
        public static string HEADERQUARTER_UPDATE_TREE_SUCCESS {
            get {
                return ResourceManager.GetString("HEADERQUARTER_UPDATE_TREE_SUCCESS", resourceCulture);
            }
        }
    }
}
