//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Resource.Tag {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationGroupSender_lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationGroupSender_lang() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMARTII.Resource.Tag.NotificationGroupSender.lang", typeof(NotificationGroupSender_lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 通知群組機制-清除個人通知 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GROUP_SENDER_CLEAR_NOTIFICATION {
            get {
                return ResourceManager.GetString("NOTIFICATION_GROUP_SENDER_CLEAR_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通知群組機制-清除個人通知失敗 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GROUP_SENDER_CLEAR_NOTIFICATION_FAIL {
            get {
                return ResourceManager.GetString("NOTIFICATION_GROUP_SENDER_CLEAR_NOTIFICATION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通知群組機制-清除個人通知成功 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GROUP_SENDER_CLEAR_NOTIFICATION_SUCCESS {
            get {
                return ResourceManager.GetString("NOTIFICATION_GROUP_SENDER_CLEAR_NOTIFICATION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通知群組機制-取得清單 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GROUP_SENDER_GET_LIST {
            get {
                return ResourceManager.GetString("NOTIFICATION_GROUP_SENDER_GET_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通知群組機制-取得清單失敗 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GROUP_SENDER_GET_LIST_FAIL {
            get {
                return ResourceManager.GetString("NOTIFICATION_GROUP_SENDER_GET_LIST_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通知群組機制-取得清單成功 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GROUP_SENDER_GET_LIST_SUCCESS {
            get {
                return ResourceManager.GetString("NOTIFICATION_GROUP_SENDER_GET_LIST_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通知群組機制-取得歷程 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GROUP_SENDER_GET_RESUME_LIST {
            get {
                return ResourceManager.GetString("NOTIFICATION_GROUP_SENDER_GET_RESUME_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通知群組機制-取得歷程失敗 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GROUP_SENDER_GET_RESUME_LIST_FAIL {
            get {
                return ResourceManager.GetString("NOTIFICATION_GROUP_SENDER_GET_RESUME_LIST_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通知群組機制-取得歷程成功 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GROUP_SENDER_GET_RESUME_LIST_SUCCESS {
            get {
                return ResourceManager.GetString("NOTIFICATION_GROUP_SENDER_GET_RESUME_LIST_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通知群組機制-取得人員 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GROUP_SENDER_GET_USER_LIST {
            get {
                return ResourceManager.GetString("NOTIFICATION_GROUP_SENDER_GET_USER_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通知群組機制-取得人員失敗 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GROUP_SENDER_GET_USER_LIST_FAIL {
            get {
                return ResourceManager.GetString("NOTIFICATION_GROUP_SENDER_GET_USER_LIST_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通知群組機制-取得人員成功 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GROUP_SENDER_GET_USER_LIST_SUCCESS {
            get {
                return ResourceManager.GetString("NOTIFICATION_GROUP_SENDER_GET_USER_LIST_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通知群組機制-不通知 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GROUP_SENDER_NO_SEND {
            get {
                return ResourceManager.GetString("NOTIFICATION_GROUP_SENDER_NO_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通知群組機制-不通知失敗 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GROUP_SENDER_NO_SEND_FAIL {
            get {
                return ResourceManager.GetString("NOTIFICATION_GROUP_SENDER_NO_SEND_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通知群組機制-不通知成功 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GROUP_SENDER_NO_SEND_SUCCESS {
            get {
                return ResourceManager.GetString("NOTIFICATION_GROUP_SENDER_NO_SEND_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通知群組機制-通知 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GROUP_SENDER_SEND {
            get {
                return ResourceManager.GetString("NOTIFICATION_GROUP_SENDER_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通知群組機制-通知失敗 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GROUP_SENDER_SEND_FAIL {
            get {
                return ResourceManager.GetString("NOTIFICATION_GROUP_SENDER_SEND_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通知群組機制-通知成功 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GROUP_SENDER_SEND_SUCCESS {
            get {
                return ResourceManager.GetString("NOTIFICATION_GROUP_SENDER_SEND_SUCCESS", resourceCulture);
            }
        }
    }
}
