//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Resource.Tag {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OfficialEmail_lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OfficialEmail_lang() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMARTII.Resource.Tag.OfficialEmail.lang", typeof(OfficialEmail_lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-管理者指派 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_ADMIN_ORDER {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_ADMIN_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-管理者指派失敗 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_ADMIN_ORDER_FAILED {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_ADMIN_ORDER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-管理者指派成功 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_ADMIN_ORDER_SUCCESS {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_ADMIN_ORDER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-認養 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_ADOPT {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_ADOPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-認養失敗 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_ADOPT_FAILED {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_ADOPT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-認養成功 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_ADOPT_SUCCESS {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_ADOPT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-自動轉派 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_AUTO_ORDER {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_AUTO_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-自動轉派失敗 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_AUTO_ORDER_FAILED {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_AUTO_ORDER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-自動轉派成功 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_AUTO_ORDER_SUCCESS {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_AUTO_ORDER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-批次認養 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_BATCHADOPT {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_BATCHADOPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-批次認養失敗 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_BATCHADOPT_FAILED {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_BATCHADOPT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-批次認養成功 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_BATCHADOPT_SUCCESS {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_BATCHADOPT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-檢查信件是否結案 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_CHECK {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-檢查信件是否結案失敗 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_CHECK_FAIL {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_CHECK_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-批次刪除 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_DELETE_RANGE {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_DELETE_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-批次刪除失敗 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_DELETE_RANGE_FAILED {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_DELETE_RANGE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-批次刪除成功 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_DELETE_RANGE_SUCCESS {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_DELETE_RANGE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-信件已認養或不存在 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_EMAIL_ALREADY_ADOPT {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_EMAIL_ALREADY_ADOPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-選取信件含案件編號 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_EMAIL_HAS_CASE {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_EMAIL_HAS_CASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-取得清單 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_GETLIST {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_GETLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-取得清單失敗 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_GETLIST_FAIL {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_GETLIST_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-批次回覆 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_REPLY_RANGE {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_REPLY_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-批次回覆失敗 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_REPLY_RANGE_FAILED {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_REPLY_RANGE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認養外部工單(email)-批次回覆成功 的當地語系化字串。
        /// </summary>
        public static string OFFICIAL_EMAIL_REPLY_RANGE_SUCCESS {
            get {
                return ResourceManager.GetString("OFFICIAL_EMAIL_REPLY_RANGE_SUCCESS", resourceCulture);
            }
        }
    }
}
