//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Resource.Tag {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PPCLIFE_Notification_lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PPCLIFE_Notification_lang() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMARTII.Resource.Tag.PPCLIFE_Notification.lang", typeof(PPCLIFE_Notification_lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 統藥大量叫修-取得NODE成功 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATIO_GET_NODE_SUCCESS {
            get {
                return ResourceManager.GetString("NOTIFICATIO_GET_NODE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統藥大量叫修-無視 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_DISREGARD {
            get {
                return ResourceManager.GetString("NOTIFICATION_DISREGARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統藥大量叫修-無視失敗 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_DISREGARD_FAIL {
            get {
                return ResourceManager.GetString("NOTIFICATION_DISREGARD_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統藥大量叫修-無視失敗，資料已異動 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_DISREGARD_FAIL_DATA_CHANG {
            get {
                return ResourceManager.GetString("NOTIFICATION_DISREGARD_FAIL_DATA_CHANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統藥大量叫修-無視成功 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_DISREGARD_SUCCESS {
            get {
                return ResourceManager.GetString("NOTIFICATION_DISREGARD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統藥大量叫修-取得清單 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GET_LIST {
            get {
                return ResourceManager.GetString("NOTIFICATION_GET_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統藥大量叫修-取得清單失敗 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GET_LIST_FAIL {
            get {
                return ResourceManager.GetString("NOTIFICATION_GET_LIST_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統藥大量叫修-取得清單成功 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GET_LIST_SUCCESS {
            get {
                return ResourceManager.GetString("NOTIFICATION_GET_LIST_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統藥大量叫修-取得NODE 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GET_NODE {
            get {
                return ResourceManager.GetString("NOTIFICATION_GET_NODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統藥大量叫修-取得NODE失敗 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_GET_NODE_FAIL {
            get {
                return ResourceManager.GetString("NOTIFICATION_GET_NODE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統藥大量叫修-通知 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_NOTICE {
            get {
                return ResourceManager.GetString("NOTIFICATION_NOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統藥大量叫修-通知失敗 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_NOTICE_FAIL {
            get {
                return ResourceManager.GetString("NOTIFICATION_NOTICE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統藥大量叫修-通知失敗，資料已異動 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_NOTICE_FAIL_DATA_CHANG {
            get {
                return ResourceManager.GetString("NOTIFICATION_NOTICE_FAIL_DATA_CHANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統藥大量叫修-通知失敗，規則個數不符合 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_NOTICE_RULE_COUNT_FAIL {
            get {
                return ResourceManager.GetString("NOTIFICATION_NOTICE_RULE_COUNT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統藥大量叫修-通知成功 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_NOTICE_SUCCESS {
            get {
                return ResourceManager.GetString("NOTIFICATION_NOTICE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統藥大量叫修-不通知 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_WHITOUT_NOTICE {
            get {
                return ResourceManager.GetString("NOTIFICATION_WHITOUT_NOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統藥大量叫修-不通知失敗 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_WHITOUT_NOTICE_FAIL {
            get {
                return ResourceManager.GetString("NOTIFICATION_WHITOUT_NOTICE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統藥大量叫修-不通知失敗，資料已異動 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_WHITOUT_NOTICE_FAIL_DATA_CHANG {
            get {
                return ResourceManager.GetString("NOTIFICATION_WHITOUT_NOTICE_FAIL_DATA_CHANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統藥大量叫修-不通知失敗，規則個數不符合 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_WHITOUT_NOTICE_RULE_COUNT_FAIL {
            get {
                return ResourceManager.GetString("NOTIFICATION_WHITOUT_NOTICE_RULE_COUNT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統藥大量叫修-不通知成功 的當地語系化字串。
        /// </summary>
        public static string NOTIFICATION_WHITOUT_NOTICE_SUCCESS {
            get {
                return ResourceManager.GetString("NOTIFICATION_WHITOUT_NOTICE_SUCCESS", resourceCulture);
            }
        }
    }
}
