//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Resource.Tag {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SysCommon_lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysCommon_lang() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMARTII.Resource.Tag.SysCommon.lang", typeof(SysCommon_lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 將此案件轉移給 {1} 的當地語系化字串。
        /// </summary>
        public static string CASE_APPLY_CASE_RESUME {
            get {
                return ResourceManager.GetString("CASE_APPLY_CASE_RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 已移轉 {1} 筆案件給您 的當地語系化字串。
        /// </summary>
        public static string CASE_APPLY_PERSONAL_NOTICE {
            get {
                return ResourceManager.GetString("CASE_APPLY_PERSONAL_NOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派客服銷案: {0}-{1} 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_CC_FINISH_RESUME {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_CC_FINISH_RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派銷案: {0} 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_FINISH_ASSIGNMENT_RESUME {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_FINISH_ASSIGNMENT_RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}-{1} 修改完成(駁回-資料重填) 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_FINISH_RESPONES_FAIL_PERSONAL_NOTIFY {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_FINISH_RESPONES_FAIL_PERSONAL_NOTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派總部、門市銷案: {0}-{1} 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_FINISH_RESUME {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_FINISH_RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寫入案件歷程、通知失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_HISTORY_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_HISTORY_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寫入轉派歷程-取得完整資訊失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_INTEGRAE_NOTICE_GET_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_INTEGRAE_NOTICE_GET_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寫入轉派歷程-傳入資訊有誤 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_INTEGRAE_NOTICE_INIT_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_INTEGRAE_NOTICE_INIT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 反應單重送: {0} 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_INVOICE_RESEND_RESUME {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_INVOICE_RESEND_RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 反應單開立: {0} 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_INVOICE_RESUME {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_INVOICE_RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派銷案駁回- {0}:{1}  的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_REJECT_ASSIGNMENT_RESUME {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_REJECT_ASSIGNMENT_RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派銷案駁回- {0}-{1}  {2}:{3}  的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_REJECT_RESUME {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_REJECT_RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派回覆:  的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_REPLY_RESUME {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_REPLY_RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉派客服銷案-重新填寫銷案資訊必須由權責單位進行 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_RESPONES_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_RESPONES_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件轉派: {0}-{1} 轉派給 {2} 知會 {3} 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_RESUME {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寫入轉派歷程失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_ASSIGNMENT_RESUME_FAIL {
            get {
                return ResourceManager.GetString("CASE_ASSIGNMENT_RESUME_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件結案 的當地語系化字串。
        /// </summary>
        public static string CASE_FINISH_RESUME {
            get {
                return ResourceManager.GetString("CASE_FINISH_RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寫入系統歷程失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_HISTORY_NOTICE_FAIL {
            get {
                return ResourceManager.GetString("CASE_HISTORY_NOTICE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寫入案件歷程、通知-取得完整資訊失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_INTEGRAE_NOTICE_GET_FAIL {
            get {
                return ResourceManager.GetString("CASE_INTEGRAE_NOTICE_GET_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寫入案件歷程、通知-傳入資訊有誤 的當地語系化字串。
        /// </summary>
        public static string CASE_INTEGRAE_NOTICE_INIT_FAIL {
            get {
                return ResourceManager.GetString("CASE_INTEGRAE_NOTICE_INIT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寫入案件歷程失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_RESUME_NOTICE_FAIL {
            get {
                return ResourceManager.GetString("CASE_RESUME_NOTICE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件建立: {0} 的當地語系化字串。
        /// </summary>
        public static string CASE_SAVE_SUCCESS_RESUME {
            get {
                return ResourceManager.GetString("CASE_SAVE_SUCCESS_RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寫入來源系統歷程失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_SOURCE_HISTORY_FAIL {
            get {
                return ResourceManager.GetString("CASE_SOURCE_HISTORY_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寫入來源歷程-取得完整資訊失敗 的當地語系化字串。
        /// </summary>
        public static string CASE_SOURCE_INTEGRAE_NOTICE_GET_FAIL {
            get {
                return ResourceManager.GetString("CASE_SOURCE_INTEGRAE_NOTICE_GET_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寫入來源歷程-傳入資訊有誤 的當地語系化字串。
        /// </summary>
        public static string CASE_SOURCE_INTEGRAE_NOTICE_INIT_FAIL {
            get {
                return ResourceManager.GetString("CASE_SOURCE_INTEGRAE_NOTICE_INIT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件解鎖 的當地語系化字串。
        /// </summary>
        public static string CASE_UNCLOSE_RESUME {
            get {
                return ResourceManager.GetString("CASE_UNCLOSE_RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件異動-新增歷程內容 的當地語系化字串。
        /// </summary>
        public static string CASE_UPDATE_ASSIGNMENT {
            get {
                return ResourceManager.GetString("CASE_UPDATE_ASSIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 消費者來信 的當地語系化字串。
        /// </summary>
        public static string EMAIL_ADOPT_CASE_ASSIGNMENT {
            get {
                return ResourceManager.GetString("EMAIL_ADOPT_CASE_ASSIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 個人認養-新增來源註記 的當地語系化字串。
        /// </summary>
        public static string EMAIL_ADOPT_CASE_SOURCE {
            get {
                return ResourceManager.GetString("EMAIL_ADOPT_CASE_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} {1} 已指派 {2} 筆官網來信案件給您 的當地語系化字串。
        /// </summary>
        public static string EMAIL_ADOPT_PERSONAL_NOTICE {
            get {
                return ResourceManager.GetString("EMAIL_ADOPT_PERSONAL_NOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 指派案件給 {1} 的當地語系化字串。
        /// </summary>
        public static string EMAIL_ASSIGN_CASE_RESUME {
            get {
                return ResourceManager.GetString("EMAIL_ASSIGN_CASE_RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 反應單取消:{0} 的當地語系化字串。
        /// </summary>
        public static string INOVICE_CANCEL {
            get {
                return ResourceManager.GetString("INOVICE_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}-{1} 已銷案 的當地語系化字串。
        /// </summary>
        public static string PERSONAL_NOTICE_CASE_ASSIGNMENT_UPDATE {
            get {
                return ResourceManager.GetString("PERSONAL_NOTICE_CASE_ASSIGNMENT_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} {1} 異動案件資訊 的當地語系化字串。
        /// </summary>
        public static string PERSONAL_NOTICE_CASE_UPDATE {
            get {
                return ResourceManager.GetString("PERSONAL_NOTICE_CASE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寫入來源歷程失敗 的當地語系化字串。
        /// </summary>
        public static string PERSONAL_NOTICE_FAIL {
            get {
                return ResourceManager.GetString("PERSONAL_NOTICE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 規則:{0}、企業別:統一藥品、商品條碼:{1}、商品名稱:{2}  因異動後未達標 的當地語系化字串。
        /// </summary>
        public static string PERSONAL_NOTIFICATION_NOTIFICATION_PPCLIFE_FAIL {
            get {
                return ResourceManager.GetString("PERSONAL_NOTIFICATION_NOTIFICATION_PPCLIFE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 規則:{0}、企業別:統一藥品、商品條碼:{1}、商品名稱:{2}、已達到示警次數:{3} 的當地語系化字串。
        /// </summary>
        public static string PERSONAL_NOTIFICATION_NOTIFICATION_PPCLIFE_SUCCESS {
            get {
                return ResourceManager.GetString("PERSONAL_NOTIFICATION_NOTIFICATION_PPCLIFE_SUCCESS", resourceCulture);
            }
        }
    }
}
