//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Resource.Tag {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class User_lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User_lang() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMARTII.Resource.Tag.User.lang", typeof(User_lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-檢查使用者姓名 的當地語系化字串。
        /// </summary>
        public static string USER_CHECK_NAME {
            get {
                return ResourceManager.GetString("USER_CHECK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-檢查使用者姓名失敗 的當地語系化字串。
        /// </summary>
        public static string USER_CHECK_NAME_FAIL {
            get {
                return ResourceManager.GetString("USER_CHECK_NAME_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-新增 的當地語系化字串。
        /// </summary>
        public static string USER_CREATE {
            get {
                return ResourceManager.GetString("USER_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-新增失敗 的當地語系化字串。
        /// </summary>
        public static string USER_CREATE_FAIL {
            get {
                return ResourceManager.GetString("USER_CREATE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-新增成功 的當地語系化字串。
        /// </summary>
        public static string USER_CREATE_SUCCESS {
            get {
                return ResourceManager.GetString("USER_CREATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-刪除照片 的當地語系化字串。
        /// </summary>
        public static string USER_DELETE_IMAGE {
            get {
                return ResourceManager.GetString("USER_DELETE_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-刪除照片失敗 的當地語系化字串。
        /// </summary>
        public static string USER_DELETE_IMAGE_FAIL {
            get {
                return ResourceManager.GetString("USER_DELETE_IMAGE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-刪除照片成功 的當地語系化字串。
        /// </summary>
        public static string USER_DELETE_IMAGE_SUCCESS {
            get {
                return ResourceManager.GetString("USER_DELETE_IMAGE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-停用 的當地語系化字串。
        /// </summary>
        public static string USER_DISABLE {
            get {
                return ResourceManager.GetString("USER_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-停用失敗 的當地語系化字串。
        /// </summary>
        public static string USER_DISABLE_FAIL {
            get {
                return ResourceManager.GetString("USER_DISABLE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-批次停用 的當地語系化字串。
        /// </summary>
        public static string USER_DISABLE_RANGE {
            get {
                return ResourceManager.GetString("USER_DISABLE_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-批次停用失敗 的當地語系化字串。
        /// </summary>
        public static string USER_DISABLE_RANGE_FAIL {
            get {
                return ResourceManager.GetString("USER_DISABLE_RANGE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-批次停用成功 的當地語系化字串。
        /// </summary>
        public static string USER_DISABLE_RANGE_SUCCESS {
            get {
                return ResourceManager.GetString("USER_DISABLE_RANGE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-停用成功 的當地語系化字串。
        /// </summary>
        public static string USER_DISABLE_SUCCESS {
            get {
                return ResourceManager.GetString("USER_DISABLE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-取得 的當地語系化字串。
        /// </summary>
        public static string USER_GET {
            get {
                return ResourceManager.GetString("USER_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-取得清單失敗 的當地語系化字串。
        /// </summary>
        public static string USER_GET_FAIL {
            get {
                return ResourceManager.GetString("USER_GET_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-取得清單 的當地語系化字串。
        /// </summary>
        public static string USER_GETLIST {
            get {
                return ResourceManager.GetString("USER_GETLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-取得清單失敗 的當地語系化字串。
        /// </summary>
        public static string USER_GETLIST_FAIL {
            get {
                return ResourceManager.GetString("USER_GETLIST_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者驗證失敗 的當地語系化字串。
        /// </summary>
        public static string USER_INVALID {
            get {
                return ResourceManager.GetString("USER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者鎖定 , 請洽系統管理員 的當地語系化字串。
        /// </summary>
        public static string USER_LOCK {
            get {
                return ResourceManager.GetString("USER_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-重置密碼 的當地語系化字串。
        /// </summary>
        public static string USER_RESET_DEFAULT_PASSWORD {
            get {
                return ResourceManager.GetString("USER_RESET_DEFAULT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-重置密碼失敗 的當地語系化字串。
        /// </summary>
        public static string USER_RESET_DEFAULT_PASSWORD_FAIL {
            get {
                return ResourceManager.GetString("USER_RESET_DEFAULT_PASSWORD_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-重置密碼成功 的當地語系化字串。
        /// </summary>
        public static string USER_RESET_DEFAULT_PASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("USER_RESET_DEFAULT_PASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-重設密碼 的當地語系化字串。
        /// </summary>
        public static string USER_RESET_PASSWORD {
            get {
                return ResourceManager.GetString("USER_RESET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-重設密碼失敗 的當地語系化字串。
        /// </summary>
        public static string USER_RESET_PASSWORD_FAIL {
            get {
                return ResourceManager.GetString("USER_RESET_PASSWORD_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-重設密碼成功 的當地語系化字串。
        /// </summary>
        public static string USER_RESET_PASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("USER_RESET_PASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-更新 的當地語系化字串。
        /// </summary>
        public static string USER_UPDATE {
            get {
                return ResourceManager.GetString("USER_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-更新失敗 的當地語系化字串。
        /// </summary>
        public static string USER_UPDATE_FAIL {
            get {
                return ResourceManager.GetString("USER_UPDATE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-更新成功 的當地語系化字串。
        /// </summary>
        public static string USER_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("USER_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-驗證AD 的當地語系化字串。
        /// </summary>
        public static string USER_VALID_AD_PASSWORD {
            get {
                return ResourceManager.GetString("USER_VALID_AD_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-驗證AD失敗 的當地語系化字串。
        /// </summary>
        public static string USER_VALID_AD_PASSWORD_FAIL {
            get {
                return ResourceManager.GetString("USER_VALID_AD_PASSWORD_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-驗證AD成功 的當地語系化字串。
        /// </summary>
        public static string USER_VALID_AD_PASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("USER_VALID_AD_PASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者版本過期 的當地語系化字串。
        /// </summary>
        public static string USER_VERSION_ERROR {
            get {
                return ResourceManager.GetString("USER_VERSION_ERROR", resourceCulture);
            }
        }
    }
}
