//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Database.SMARTII
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL_BOARD
    {
        public int ID { get; set; }
        public System.DateTime ACTIVE_DATE_START { get; set; }
        public System.DateTime ACTIVE_DATE_END { get; set; }
        public string CONTENT { get; set; }
        public string FILE_PATH { get; set; }
        public string TITLE { get; set; }
        public byte WARNING_TYPE { get; set; }
        public string CREATE_USERNAME { get; set; }
        public string CREATE_USER_ID { get; set; }
        public System.DateTime CREATE_DATETIME { get; set; }
        public string UPDATE_USERNAME { get; set; }
        public string UPDATE_USER_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATETIME { get; set; }
        public string USER_IDs { get; set; }
        public bool IS_NOTIFICATED { get; set; }
    }
}
