//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Database.SMARTII
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASE_ASSIGNMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CASE_ASSIGNMENT()
        {
            this.CASE_ASSIGNMENT_CONCAT_USER = new HashSet<CASE_ASSIGNMENT_CONCAT_USER>();
            this.CASE_ASSIGNMENT_USER = new HashSet<CASE_ASSIGNMENT_USER>();
        }
    
        public int ASSIGNMENT_ID { get; set; }
        public string CASE_ID { get; set; }
        public int NODE_ID { get; set; }
        public byte ORGANIZATION_TYPE { get; set; }
        public string CONTENT { get; set; }
        public string FILE_PATH { get; set; }
        public string FINISH_CONTENT { get; set; }
        public string FINISH_FILE_PATH { get; set; }
        public Nullable<System.DateTime> FINISH_DATETIME { get; set; }
        public string FINISH_USERNAME { get; set; }
        public Nullable<int> FINISH_NODE_ID { get; set; }
        public string FINISH_NODE_NAME { get; set; }
        public Nullable<byte> FINISH_ORGANIZATION_TYPE { get; set; }
        public string NOTIFICATION_BEHAVIORS { get; set; }
        public Nullable<System.DateTime> NOTICE_DATETIME { get; set; }
        public string NOTICE_USERs { get; set; }
        public byte CASE_ASSIGNMENT_TYPE { get; set; }
        public System.DateTime CREATE_DATETIME { get; set; }
        public string CREATE_USERNAME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATETIME { get; set; }
        public string UPDATE_USERNAME { get; set; }
        public string EML_FILE_PATH { get; set; }
        public byte REJECT_TYPE { get; set; }
        public string REJECT_REASON { get; set; }
        public int RECALL_TIMEs { get; set; }
    
        public virtual CASE CASE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASE_ASSIGNMENT_CONCAT_USER> CASE_ASSIGNMENT_CONCAT_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASE_ASSIGNMENT_USER> CASE_ASSIGNMENT_USER { get; set; }
    }
}
