//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Database.SMARTII
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASE_REMIND
    {
        public int ID { get; set; }
        public string CASE_ID { get; set; }
        public Nullable<int> ASSIGNMENT_ID { get; set; }
        public int NODE_ID { get; set; }
        public byte ORGANIZATION_TYPE { get; set; }
        public System.DateTime ACTIVE_START_DAETTIME { get; set; }
        public System.DateTime ACTIVE_END_DAETTIME { get; set; }
        public string CONTENT { get; set; }
        public string USER_IDs { get; set; }
        public bool IS_CONFIRM { get; set; }
        public bool IS_NOTIFCATED { get; set; }
        public string CONFIRM_USER_ID { get; set; }
        public Nullable<System.DateTime> CONFIRM_DATETIME { get; set; }
        public string CONFIRM_USERNAME { get; set; }
        public byte TYPE { get; set; }
        public string CREATE_USER_ID { get; set; }
        public string CREATE_USERNAME { get; set; }
        public System.DateTime CREATE_DATETIME { get; set; }
        public string UPDATE_USERNAME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATETIME { get; set; }
    
        public virtual CASE CASE { get; set; }
    }
}
