//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Database.SMARTII
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASE_ASSIGN_GROUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CASE_ASSIGN_GROUP()
        {
            this.CASE_ASSIGN_GROUP_USER = new HashSet<CASE_ASSIGN_GROUP_USER>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public int NODE_ID { get; set; }
        public byte ORGANIZATION_TYPE { get; set; }
        public byte TYPE { get; set; }
        public System.DateTime CREATE_DATETIME { get; set; }
        public string CREATE_USERNAME { get; set; }
        public string UPDATE_USERNAME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATETIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASE_ASSIGN_GROUP_USER> CASE_ASSIGN_GROUP_USER { get; set; }
    }
}
