//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Database.SMARTII
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASE_ITEM
    {
        public string CASE_ID { get; set; }
        public int ITEM_ID { get; set; }
        public string JCONTENT { get; set; }
    
        public virtual CASE CASE { get; set; }
        public virtual ITEM ITEM { get; set; }
    }
}
