//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Database.SMARTII
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CASE()
        {
            this.CASE_ASSIGNMENT = new HashSet<CASE_ASSIGNMENT>();
            this.CASE_ASSIGNMENT_COMMUNICATE = new HashSet<CASE_ASSIGNMENT_COMMUNICATE>();
            this.CASE_ASSIGNMENT_COMPLAINT_INVOICE = new HashSet<CASE_ASSIGNMENT_COMPLAINT_INVOICE>();
            this.CASE_ASSIGNMENT_COMPLAINT_NOTICE = new HashSet<CASE_ASSIGNMENT_COMPLAINT_NOTICE>();
            this.CASE_COMPLAINED_USER = new HashSet<CASE_COMPLAINED_USER>();
            this.CASE_CONCAT_USER = new HashSet<CASE_CONCAT_USER>();
            this.CASE_ITEM = new HashSet<CASE_ITEM>();
            this.CASE_REMIND = new HashSet<CASE_REMIND>();
            this.CASE_FINISH_REASON_DATA = new HashSet<CASE_FINISH_REASON_DATA>();
            this.CASE_TAG = new HashSet<CASE_TAG>();
        }
    
        public string CASE_ID { get; set; }
        public int NODE_ID { get; set; }
        public byte ORGANIZATION_TYPE { get; set; }
        public string SOURCE_ID { get; set; }
        public string APPLY_USERNAME { get; set; }
        public Nullable<System.DateTime> APPLY_DAETTIME { get; set; }
        public string APPLY_USER_ID { get; set; }
        public string CONTENT { get; set; }
        public byte CASE_TYPE { get; set; }
        public Nullable<System.DateTime> PROMISE_DATETIME { get; set; }
        public Nullable<System.DateTime> EXPECT_DATETIME { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
        public string FINISH_CONTENT { get; set; }
        public string FINISH_FILE_PATH { get; set; }
        public Nullable<System.DateTime> FINISH_DATETIME { get; set; }
        public string FINISH_EML_FILE_PATH { get; set; }
        public string FINISH_USERNAME { get; set; }
        public Nullable<System.DateTime> FINISH_REPLY_DATETIME { get; set; }
        public bool IS_REPORT { get; set; }
        public bool IS_ATTENSION { get; set; }
        public int QUESION_CLASSIFICATION_ID { get; set; }
        public int CASE_WARNING_ID { get; set; }
        public string RELATION_CASE_IDs { get; set; }
        public System.DateTime CREATE_DATETIME { get; set; }
        public string CREATE_USERNAME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATETIME { get; set; }
        public string UPDATE_USERNAME { get; set; }
        public string J_CONTENT { get; set; }
        public string EML_FILE_PATH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASE_ASSIGNMENT> CASE_ASSIGNMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASE_ASSIGNMENT_COMMUNICATE> CASE_ASSIGNMENT_COMMUNICATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASE_ASSIGNMENT_COMPLAINT_INVOICE> CASE_ASSIGNMENT_COMPLAINT_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASE_ASSIGNMENT_COMPLAINT_NOTICE> CASE_ASSIGNMENT_COMPLAINT_NOTICE { get; set; }
        public virtual CASE_SOURCE CASE_SOURCE { get; set; }
        public virtual CASE_WARNING CASE_WARNING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASE_COMPLAINED_USER> CASE_COMPLAINED_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASE_CONCAT_USER> CASE_CONCAT_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASE_ITEM> CASE_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASE_REMIND> CASE_REMIND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASE_FINISH_REASON_DATA> CASE_FINISH_REASON_DATA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASE_TAG> CASE_TAG { get; set; }
    }
}
