//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Database.SMARTII
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASE_FINISH_REASON_DATA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CASE_FINISH_REASON_DATA()
        {
            this.CASE = new HashSet<CASE>();
        }
    
        public int ID { get; set; }
        public int CLASSIFICATION_ID { get; set; }
        public string TEXT { get; set; }
        public bool IS_ENABLED { get; set; }
        public System.DateTime CREATE_DATETIME { get; set; }
        public string CREATE_USERNAME { get; set; }
        public string UPDATE_USERNAME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATETIME { get; set; }
        public int ORDER { get; set; }
        public Nullable<bool> DEFAULT { get; set; }
    
        public virtual CASE_FINISH_REASON_CLASSIFICATION CASE_FINISH_REASON_CLASSIFICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASE> CASE { get; set; }
    }
}
