//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Database.SMARTII
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JOB()
        {
            this.NODE_JOB = new HashSet<NODE_JOB>();
        }
    
        public int ID { get; set; }
        public int DEFINITION_ID { get; set; }
        public string NAME { get; set; }
        public System.DateTime CREATE_DATETIME { get; set; }
        public string CREATE_USERNAME { get; set; }
        public string UPDATE_USERNAME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATETIME { get; set; }
        public byte ORGANIZATION_TYPE { get; set; }
        public bool IS_ENABLED { get; set; }
        public int LEVEL { get; set; }
        public string KEY { get; set; }
    
        public virtual ORGANIZATION_NODE_DEFINITION ORGANIZATION_NODE_DEFINITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NODE_JOB> NODE_JOB { get; set; }
    }
}
