//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Database.SMARTII
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATION_GROUP_EFFECTIVE_SUMMARY
    {
        public int ID { get; set; }
        public int NOTIFICATION_GROUP_ID { get; set; }
        public int EXPECT_ARRIVE_COUNT { get; set; }
        public int ACTUAL_ARRIVE_COUNT { get; set; }
        public string CASE_IDs { get; set; }
        public System.DateTime CREATE_DATETIME { get; set; }
        public bool IS_PROCESS { get; set; }
        public Nullable<System.DateTime> UPDATE_DATETIME { get; set; }
        public string UPDATE_USERNAME { get; set; }
    }
}
