//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Database.SMARTII
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATION_GROUP_RESUME
    {
        public int ID { get; set; }
        public int GROUP_ID { get; set; }
        public string NODE_NAME { get; set; }
        public int NODE_ID { get; set; }
        public string TARGET { get; set; }
        public string CONTENT { get; set; }
        public byte TYPE { get; set; }
        public System.DateTime CREATE_DATETIME { get; set; }
        public string CREATE_USERNAME { get; set; }
        public string EML_FILE_PATH { get; set; }
    
        public virtual NOTIFICATION_GROUP NOTIFICATION_GROUP { get; set; }
    }
}
