//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Database.SMARTII
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFICIAL_EMAIL_GROUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OFFICIAL_EMAIL_GROUP()
        {
            this.USER = new HashSet<USER>();
        }
    
        public int ID { get; set; }
        public Nullable<int> NODE_ID { get; set; }
        public Nullable<byte> ORGANIZATION_TYPE { get; set; }
        public string MAIL_ADDRESS { get; set; }
        public string MAIL_DISPLAY_NAME { get; set; }
        public string OFFICIAL_EMAIL { get; set; }
        public string ACCOUNT { get; set; }
        public string PASSWORD { get; set; }
        public System.DateTime CREATE_DATETIME { get; set; }
        public string CREATE_USERNAME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATETIME { get; set; }
        public string UPDATE_USERNAME { get; set; }
        public int KEEP_DAY { get; set; }
        public byte PROTOCOL { get; set; }
        public string HOSTNAME { get; set; }
        public bool IS_ENABLED { get; set; }
        public bool ALLOW_RECEIVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USER { get; set; }
    }
}
