//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Database.SMARTII
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFICIAL_EMAIL_EFFECTIVE_DATA
    {
        public int NODE_ID { get; set; }
        public byte ORGANIZATION_TYPE { get; set; }
        public string MESSAGE_ID { get; set; }
        public string SUBJECT { get; set; }
        public string FROM_NAME { get; set; }
        public string FROM_ADDRESS { get; set; }
        public string BODY { get; set; }
        public System.DateTime RECEIVED_DATETIME { get; set; }
        public string FILE_PATH { get; set; }
        public System.DateTime CREATE_DATETIME { get; set; }
        public string CASE_ID { get; set; }
        public int EMAIL_GROUP_ID { get; set; }
        public bool HAS_ATTACHMENT { get; set; }
        public string J_CONTENT { get; set; }
    }
}
