//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Database.SMARTII
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGANIZATION_NODE_DEFINITION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORGANIZATION_NODE_DEFINITION()
        {
            this.CALLCENTER_NODE = new HashSet<CALLCENTER_NODE>();
            this.HEADQUARTERS_NODE = new HashSet<HEADQUARTERS_NODE>();
            this.JOB = new HashSet<JOB>();
            this.VENDOR_NODE = new HashSet<VENDOR_NODE>();
        }
    
        public byte ORGANIZATION_TYPE { get; set; }
        public int ID { get; set; }
        public string NAME { get; set; }
        public System.DateTime CREATE_DATETIME { get; set; }
        public string CREATE_USERNAME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATETIME { get; set; }
        public string UPDATE_USERNAME { get; set; }
        public bool IS_ENABLED { get; set; }
        public Nullable<int> IDENTIFICATION_ID { get; set; }
        public string IDENTIFICATION_NAME { get; set; }
        public int LEVEL { get; set; }
        public string KEY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALLCENTER_NODE> CALLCENTER_NODE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HEADQUARTERS_NODE> HEADQUARTERS_NODE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOB> JOB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENDOR_NODE> VENDOR_NODE { get; set; }
    }
}
