//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Database.SMARTII
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPCLIFE_EFFECTIVE_SUMMARY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PPCLIFE_EFFECTIVE_SUMMARY()
        {
            this.CASE_PPCLIFE = new HashSet<CASE_PPCLIFE>();
        }
    
        public int ID { get; set; }
        public byte ARRIVE_TYPE { get; set; }
        public int ITEM_ID { get; set; }
        public string BATCH_NO { get; set; }
        public System.DateTime CREATE_DATETIME { get; set; }
        public string CREATE_USERNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASE_PPCLIFE> CASE_PPCLIFE { get; set; }
    }
}
