//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Database.SMARTII
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORE
    {
        public int NODE_ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public System.DateTime CREATE_DATETIME { get; set; }
        public string CREATE_USERNAME { get; set; }
        public string UPDATE_USERNAME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATETIME { get; set; }
        public string J_CONTENT { get; set; }
        public byte ORGANIZATION_TYPE { get; set; }
        public string TELEPHONE { get; set; }
        public string ADDRESS { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> STORE_OPEN_DATETIME { get; set; }
        public Nullable<System.DateTime> STORE_CLOSE_DATETIME { get; set; }
        public Nullable<int> STORE_TYPE { get; set; }
        public string MEMO { get; set; }
        public Nullable<bool> IS_ENABLED { get; set; }
        public string SERVICE_TIME { get; set; }
        public Nullable<int> OWNER_NODE_JOB_ID { get; set; }
        public Nullable<int> SUPERVISOR_NODE_JOB_ID { get; set; }
    
        public virtual HEADQUARTERS_NODE HEADQUARTERS_NODE { get; set; }
    }
}
