//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Database.SMARTII
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_PARAMETER
    {
        public string USER_ID { get; set; }
        public bool NAVIGATE_OF_NEWBIE { get; set; }
        public bool NOTICE_OF_WEBSITE { get; set; }
        public string FAVORITE_FEATURE { get; set; }
        public string IMAGE_PATH { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
