//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Database.SMARTII
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_KM_CLASSIFICATION_NESTED
    {
        public long INDEX { get; set; }
        public Nullable<int> NODE_ID { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<byte> ORGANIZATION_TYPE { get; set; }
        public Nullable<int> LEVEL { get; set; }
        public string PARENT_PATH { get; set; }
        public string PARENT_PATH_NAME { get; set; }
    }
}
