//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTII.Database.SMARTII
{
    using System;
    using System.Collections.Generic;
    
    public partial class 組織與職稱
    {
        public int ID { get; set; }
        public int JOB_ID { get; set; }
        public int NODE_ID { get; set; }
        public int RIGHT_BOUNDARY { get; set; }
        public int LEFT_BOUNDARY { get; set; }
        public byte ORGANIZATION_TYPE { get; set; }
        public Nullable<int> IDENTIFICATION { get; set; }
        public string JOB_NAME { get; set; }
        public string NODE_NAME { get; set; }
    }
}
