


CREATE VIEW [dbo].[VW_KM_CLASSIFICATION_NESTED] WITH SCHEMABINDING  AS 
WITH KM_CLASSIFICATION_NESTED(
    NODE_ID,
	ID ,
    PARENT_ID ,
    [NAME],
    ORGANIZATION_TYPE,
    LEVEL,
    PARENT_PATH,
    PARENT_PATH_NAME)
AS(
 SELECT
    NODE_ID ,
    ID ,
    PARENT_ID ,
    [NAME],
    ORGANIZATION_TYPE ,
    1 AS LEVEL,
    CONVERT(nvarchar(128), ID) AS PARENT_PATH,
    CONVERT(nvarchar(128), [NAME]) AS  PARENT_PATH_NAME
 FROM [dbo].KM_CLASSIFICATION
 WHERE PARENT_ID IS NULL
 UNION ALL
 SELECT
   S.NODE_ID ,
    S.ID ,
    S.PARENT_ID ,
    S.[NAME],
    S.ORGANIZATION_TYPE ,
    P.LEVEL + 1 AS LEVEL ,
    CONVERT(nvarchar(128), CONVERT(nvarchar(128),S.ID) + '/' + P.PARENT_PATH),
    CONVERT(nvarchar(128), S.NAME + '/' +  P.PARENT_PATH_NAME)
 FROM [dbo].KM_CLASSIFICATION S
 JOIN KM_CLASSIFICATION_NESTED P
 ON S.PARENT_ID = P.ID
)
SELECT 
    ISNULL(row_number() over(order by ID),0) as [INDEX],
    NODE_ID,
	ID ,
    PARENT_ID ,
    [NAME],
    ORGANIZATION_TYPE,
    LEVEL,
    PARENT_PATH,
    PARENT_PATH_NAME FROM KM_CLASSIFICATION_NESTED 
